import sys
# Force line-buffered stdout so every print() flushes immediately to the log file.
# Without this, Python buffers output when stdout is a pipe (not a terminal),
# which means the SSE stream sees nothing until the 8 KB buffer fills up.
sys.stdout.reconfigure(line_buffering=True)

import torch
import torch_geometric.transforms as T
from torch_geometric.loader import DataLoader
import numpy as np
from dataset import FpcDataset
import os
import json
import argparse
import tqdm
from torch.utils.tensorboard.writer import SummaryWriter
from utils.utils import NodeType

# ── Config: defaults, overridable via --config JSON (used by UI) ──────────────
_defaults = dict(
    domain                   = 'cylinder_flow',
    dataset_dir              = 'data',
    batch_size               = 20,
    noise_std                = 2e-2,
    num_epochs               = 100,
    early_stopping_patience  = 10,
    lr                       = 1e-4,
    message_passing_num      = 15,
    checkpoint_dir           = 'checkpoints',
    log_dir                  = 'runs',
    # Derived from domain if not provided:
    output_size              = None,   # set automatically from domain: 2 (cylinder_flow) or 3 (flag_simple)
    node_input_size          = None,   # 11 = CFD velocity, 12 = cloth
    edge_input_size          = None,   # 3 = CFD, 7 = cloth
)

parser = argparse.ArgumentParser()
parser.add_argument('--config', type=str, default=None,
                    help='Path to JSON config file (generated by UI)')
args, _ = parser.parse_known_args()

cfg = dict(_defaults)
if args.config and os.path.exists(args.config):
    with open(args.config) as f:
        cfg.update(json.load(f))

# ── Domain defaults ────────────────────────────────────────────────────────────
_DOMAIN_DEFAULTS = {
    'cylinder_flow': dict(output_size=2, node_input_size=11, edge_input_size=3),
    'flag_simple':   dict(output_size=3, node_input_size=12, edge_input_size=7),
}
domain = cfg['domain']
if domain not in _DOMAIN_DEFAULTS:
    raise ValueError(f"Unknown domain '{domain}'. Valid: {list(_DOMAIN_DEFAULTS)}")

# Fill in derived sizes if not explicitly provided
for key, val in _DOMAIN_DEFAULTS[domain].items():
    if cfg.get(key) is None:
        cfg[key] = val

target_field = cfg.get('target_field', 'velocity')

# Pressure mode overrides cylinder_flow defaults
if domain == 'cylinder_flow' and target_field == 'pressure':
    cfg['output_size']     = 1
    cfg['node_input_size'] = 10
    cfg['edge_input_size'] = 3

output_size     = cfg['output_size']
node_input_size = cfg['node_input_size']
edge_input_size = cfg['edge_input_size']

dataset_dir             = cfg['dataset_dir']
batch_size              = cfg['batch_size']
noise_std               = cfg['noise_std']
num_epochs              = cfg['num_epochs']
early_stopping_patience = cfg['early_stopping_patience']
checkpoint_dir          = cfg['checkpoint_dir']
log_dir                 = cfg['log_dir']

device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
os.makedirs(checkpoint_dir, exist_ok=True)
os.makedirs(log_dir, exist_ok=True)

# 初始化模型与优化器
if domain == 'flag_simple':
    from model.flag_simulator import FlagSimulator
    simulator = FlagSimulator(
        message_passing_num=cfg['message_passing_num'],
        device=device
    )
    transformer = None  # FlagSimulator builds edges internally
else:
    from model.simulator import Simulator
    simulator = Simulator(
        message_passing_num=cfg['message_passing_num'],
        node_input_size=node_input_size,
        edge_input_size=edge_input_size,
        device=device,
        target_field=target_field,
    )
    transformer = T.Compose([
        T.FaceToEdge(),
        T.Cartesian(norm=False),
        T.Distance(norm=False)
    ])

optimizer = torch.optim.Adam(simulator.parameters(), lr=cfg['lr'])
print('Optimizer initialized')

# TensorBoard writer
writer = SummaryWriter(log_dir=log_dir)

def load_checkpoint(checkpoint_path, model, optimizer, device):
    """Resume training from a saved checkpoint."""
    if not os.path.exists(checkpoint_path):
        print('No checkpoint found, starting from scratch.')
        return 1, float('inf')
    ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)
    ckpt_domain = ckpt.get('domain', 'cylinder_flow')  # old checkpoints default to cfd
    if ckpt_domain != domain:
        raise RuntimeError(
            f"Checkpoint domain '{ckpt_domain}' does not match current domain '{domain}'. "
            "Delete the checkpoint or update --config to match the checkpoint domain."
        )
    ckpt_target_field = ckpt.get('target_field', 'velocity')  # old checkpoints default to velocity
    if ckpt_target_field != target_field:
        raise RuntimeError(
            f"Checkpoint target_field '{ckpt_target_field}' does not match current "
            f"target_field '{target_field}'. Delete the checkpoint or update --config."
        )
    model.load_state_dict(ckpt['model_state_dict'])
    optimizer.load_state_dict(ckpt['optimizer_state_dict'])
    start_epoch = ckpt['epoch'] + 1
    best_valid_loss = ckpt['valid_loss']
    print(f'Resumed from epoch {ckpt["epoch"]} with valid loss {best_valid_loss:.2e}')
    return start_epoch, best_valid_loss

def train_one_epoch(model, dataloader, optimizer, transformer, device, noise_std, domain, target_field="velocity"):
    assert target_field in ("velocity", "pressure"), f"Unknown target_field: {target_field!r}"
    model.train()
    total_loss = 0.0
    num_batches = 0

    for graph in tqdm.tqdm(dataloader):
        if transformer is not None:
            graph = transformer(graph)
        graph = graph.to(device)

        if domain == 'flag_simple':
            predicted_acc, target_acc = model(graph)
            # Cloth: loss on NORMAL nodes only
            node_type = graph.x[:, 3].long()
            mask = (node_type == NodeType.NORMAL)
        else:
            from utils.noise import get_velocity_noise
            velocity_sequence_noise = get_velocity_noise(graph, noise_std=noise_std, device=device)
            # Trim noise width to match field: [N,1] for pressure, [N,2] for velocity
            if domain == 'cylinder_flow' and target_field == 'pressure':
                velocity_sequence_noise = velocity_sequence_noise[:, :1]
            predicted_acc, target_acc = model(graph, velocity_sequence_noise)
            node_type = graph.x[:, 0]
            mask = torch.logical_or(node_type == NodeType.NORMAL, node_type == NodeType.OUTFLOW)

        errors = ((predicted_acc - target_acc) ** 2)[mask]
        loss = torch.mean(errors)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        num_batches += 1

    return total_loss / num_batches


def evaluate(model, dataloader, transformer, device, domain):
    model.eval()
    losses = []

    with torch.no_grad():
        for graph in dataloader:
            if transformer is not None:
                graph = transformer(graph)
            graph = graph.to(device)

            if domain == 'flag_simple':
                # In eval mode, FlagSimulator returns next_world_pos
                next_world_pos = model(graph)
                node_type = graph.x[:, 3].long()
                mask = (node_type == NodeType.NORMAL)
                errors = ((next_world_pos - graph.y) ** 2)[mask]
            else:
                predicted_velocity = model(graph, None)
                node_type = graph.x[:, 0]
                mask = torch.logical_or(node_type == NodeType.NORMAL, node_type == NodeType.OUTFLOW)
                errors = ((predicted_velocity - graph.y) ** 2)[mask]

            loss = torch.sqrt(torch.mean(errors))
            losses.append(loss.item())

    return np.mean(losses)


if __name__ == '__main__':
    # 加载训练和验证数据集
    if domain == 'flag_simple':
        from dataset.flag_dataset import FlagDataset
        train_dataset = FlagDataset(data_root=cfg['dataset_dir'], split='train')
        valid_dataset = FlagDataset(data_root=cfg['dataset_dir'], split='valid')
    else:
        train_dataset = FpcDataset(data_root=dataset_dir, split='train',
                                   target_field=target_field)
        valid_dataset = FpcDataset(data_root=dataset_dir, split='valid',
                                   target_field=target_field)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                              num_workers=2, pin_memory=False)
    valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False,
                              num_workers=2, pin_memory=False)

    simulator.to(device)

    # Resume from checkpoint if it exists — use domain-specific filename to
    # avoid collisions between cylinder_flow and flag_simple checkpoints.
    ckpt_filename = "flag_best_model.pth" if domain == "flag_simple" else "best_model.pth"
    checkpoint_path = os.path.join(checkpoint_dir, ckpt_filename)
    start_epoch, best_valid_loss = load_checkpoint(checkpoint_path, simulator, optimizer, device)
    best_epoch = start_epoch - 1
    epochs_no_improve = 0

    for epoch in range(start_epoch, num_epochs + 1):

        train_loss = train_one_epoch(simulator, train_loader, optimizer, transformer, device, noise_std, domain, target_field)
        valid_loss = evaluate(simulator, valid_loader, transformer, device, domain)

        print(f"Epoch {epoch}/{num_epochs} Train Loss: {train_loss:.2e} Valid Loss: {valid_loss:.2e}")

        # 👇 TensorBoard
        writer.add_scalar('Loss/train', train_loss, epoch)
        writer.add_scalar('Loss/valid', valid_loss, epoch)

        # 保存最优模型
        if valid_loss < best_valid_loss:
            best_valid_loss = valid_loss
            best_epoch = epoch
            epochs_no_improve = 0
            torch.save({
                'epoch':                epoch,
                'model_state_dict':     simulator.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'valid_loss':           valid_loss,
                'domain':               domain,
                'target_field':         target_field,
                'output_size':          output_size,
                'node_input_size':      node_input_size,
                'edge_input_size':      edge_input_size,
            }, checkpoint_path)
            print(f"  -> New best model saved at epoch {epoch} with valid loss {valid_loss:.2e}")
        else:
            epochs_no_improve += 1
            print(f"  -> No improvement for {epochs_no_improve}/{early_stopping_patience} epochs")
            if epochs_no_improve >= early_stopping_patience:
                print(f"\nEarly stopping triggered. No improvement for {early_stopping_patience} epochs.")
                break

    writer.close()

    # ── Build confidence index (optional, default enabled) ────────────────────────
    if cfg.get('build_confidence_index', True):
        try:
            print("\nBuilding confidence index on training set...")
            from confidence.index import NearestNeighborIndex
            from model.embedding import extract_embedding
            from torch_geometric.loader import DataLoader as SingleLoader

            embeddings = []
            simulator.eval()
            single_loader = SingleLoader(train_dataset, batch_size=1, shuffle=False, num_workers=0)
            for graph in tqdm.tqdm(single_loader, desc='Extracting embeddings'):
                if transformer is not None:
                    graph = transformer(graph)
                emb = extract_embedding(simulator, graph, device=device)
                embeddings.append(emb)

            embeddings_arr = np.stack(embeddings)   # [N_train, 128]
            index = NearestNeighborIndex()
            index.build(embeddings_arr)
            index_path = os.path.join(log_dir, 'embedding_index.pkl')
            index.save(index_path)
            print("Confidence index saved to %s (backend: %s, diameter: %.4f, N=%d)" % (
                index_path, index.backend, index.train_diameter, len(embeddings)))
        except Exception as e:
            print("Warning: confidence index build failed (non-fatal): %s" % e)

    print(f"\nTraining finished. Best model at epoch {best_epoch} with validation loss {best_valid_loss:.2e}")
